eos-01:
  hostname: 192.168.100.11
  groups:
    - arista
  data:
    interfaces:
      - name: eth1
        description: eos-03
        ip: 10.1.1.1/30
      - name: eth2
        description: eos-04
        ip: 10.1.2.1/30
      - name: eth3
        description: eos-05 
        ip: 10.1.3.1/30
  bgp:
    asn: 65000
    neighbours:
      - ip: 10.1.1.2
        asn: 65001
      - ip: 10.1.2.2
        asn: 65002
      - ip: 10.1.3.2
        asn: 65003
eos-02:
  hostname: 192.168.100.12
  groups:
    - arista
  data:
    interfaces:
      - name: eth1
        description: eos-03
        ip: 10.2.1.1/30
      - name: eth2
        description: eos-04
        ip: 10.2.2.1/30
      - name: eth3
        description: eos-05
        ip: 10.2.3.1/30
  bgp:
    asn: 65000
    neighbours:
      - ip: 10.2.1.2
        asn: 65001
      - ip: 10.2.2.2
        asn: 65002
      - ip: 10.2.3.2
        asn: 65003
eos-03:
  hostname: 192.168.100.13
  groups:
    - arista
  data:
    interfaces:
      - name: eth1
        description: eos-01
        ip: 10.1.1.2/30
      - name: eth2
        description: eos-02
        ip: 10.2.1.2/30
    bgp:
      asn: 65001
      neighbours:
        - ip: 10.1.1.1
          asn: 65000
        - ip: 10.2.1.1
          asn: 65000
eos-04:
  hostname: 192.168.100.14
  groups:
    - arista
  data:
    interfaces:
      - name: eth1
        description: eos-01
        ip: 10.1.2.2/30
      - name: eth2
        description: eos-02
        ip: 10.2.2.2/30
    bgp:
      asn: 65002
      neighbours:
        - ip: 10.1.2.1
          asn: 65000
        - ip: 10.2.2.1
          asn: 65000
eos-05:
  hostname: 192.168.100.15
  groups:
    - arista
  data:
    interfaces:
      - name: eth1
        description: eos-01
        ip: 10.1.3.2/30
      - name: eth2
        description: eos-02
        ip: 10.2.3.2/30
    bgp:
      asn: 65003
      neighbours:
        - ip: 10.1.3.1
          asn: 65000
        - ip: 10.2.3.1
          asn: 65000
